# Generated by Django 5.1.6 on 2025-03-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_postcategory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.postcategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='entry',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
