# Generated by Django 5.1.6 on 2025-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(null=True, upload_to='forum/images/'),
        ),
    ]
