# Generated by Django 5.2 on 2025-05-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_product_owner_alter_transaction_buyer_and_more'),
        ('user_management', '0002_rename_email_address_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user_management.profile'),
            preserve_default=False,
        ),
    ]
