# Generated by Django 5.1.6 on 2025-05-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-status', 'created_on']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-status', '-manpower_required', 'role']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-status', '-applied_on']},
        ),
    ]
