# Generated by Django 5.1.6 on 2025-05-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={},
        ),
    ]
