# Generated by Django 4.2.10 on 2025-05-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={},
        ),
    ]
