# Generated by Django 5.1.6 on 2025-05-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_articlecategory_options_alter_article_category'),
        ('wiki', '0004_article_author_article_image_comment'),
    ]

    operations = [
    ]
