# Generated by Django 5.1.6 on 2025-05-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_article_author_alter_comment_author_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='header_image',
        ),
    ]
