# Generated by Django 5.1.6 on 2025-05-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(upload_to='wiki/images/'),
        ),
    ]
