# Generated by Django 5.1.6 on 2025-05-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='wiki/images/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='wiki.article')),
            ],
        ),
    ]
