# Generated by Django 5.1.6 on 2025-05-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_articleimage_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
