# Generated by Django 5.1.6 on 2025-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.FileField(blank=True, null=True, upload_to='blog/images/'),
        ),
    ]
