# Generated by Django 5.1.6 on 2025-05-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_alter_articlecategory_options'),
        ('blog', '0009_alter_comment_author_alter_gallery_image'),
    ]

    operations = [
    ]
