# Generated by Django 4.2 on 2025-05-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_merge_20250514_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(upload_to='blog/images/'),
        ),
    ]
